apiVersion: v1
kind: Service
metadata:
  name: random-pod
  labels:
    run: random-pod
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: rand-pod