apiVersion: apps/v1
kind: Deployment
metadata:
  name: rand-deployment
  labels:
    app: rand
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rand-pod
  template:
    metadata:
      labels:
        app: rand-pod
    spec:
      containers:
      - name: random-pod
        image: 192.168.56.105:5000/random_number:prod
        imagePullPolicy: "Always"
        ports:
          - containerPort: 8000
        resources:
          requests:
            cpu: 200m
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rand-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rand-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20