apiVersion: v1
kind: Pod
metadata:
  name: sum-pod
  labels:
     app: sum-pod
spec:
  containers:
    - name: sum-pod
      image: 192.168.56.105:5000/sum_number:latest
      env:
        - name: RN_HOST
          value: "random-pod"
        - name: RN_PORT
          value: "8000"
      ports:
        - containerPort: 8000